name: Search and alert for jobs

on:
  schedule:
    - cron: "0 6,9,12,15 * * *"
  workflow_dispatch:

jobs:
  search_for_jobs_and_notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install  
      - name: Run Node.js application
        env:
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          SMTP_TO: ${{ secrets.SMTP_TO }}
        run: npm start
